
services:
  app:
    build: .
    container_name: my-nestjs-app
    ports:
      - "3000:3000"

  mysql:
    image: mysql:8.0
    container_name: my-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myprojectdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
